### PR TITLE
DeviceAgent: improve support for inspecting app state and terminating apps

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

DELETE /session should terminate the AUT, but this is not working.

When POST /session is passed :terminate_aut_if_running => true, the app is terminated if it is running.

Both routes call the same Testmanagerd#_XTC_terminate method - this is working, there are integration tests.

I had no integration tests for the DELETE /session route until now.

Completes:

* RunLoop: needs public API for POST /terminate route [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29181)
* run-loop: DeviceAgent::Client#server_pid returns pid of AUT [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29182)

Progress on:

* Every 2nd test failing with UITest on iOS 11 devices [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/24253)
* DeviceAgent: App#terminate does not work in the context of DELETE /session [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/29177)

### CODE REVIEW

**Comment by jmoody** [comment]
ATTN @maxelrod

I cannot add you as a reviewer until you accept the invite.

I am going to merge this after CI is complete.  If you have a chance, take a look and make comments. 

Thanks!

**Comment by maxelrod** [comment]
It looks ok to me, but I am unclear as to why you expect a server 300 response?

**Comment by jmoody** [comment]
> expect_300_response

This method name can be improved.  The client (run-loop) should accept HTTP response codes < 400.

Maybe these are better:

```
* expect_success_or_redirect_response
* expect_less_than_400_response
```

Can you suggest a better name?

Thanks for reviewing!

**Comment by maxelrod** [comment]
I think the first option is best as it is clearest.

**Comment by jmoody** [comment]
Would you like to do a refactor/rename pull request?

**Pull request merged**
