### PR TITLE
Extract Logger and onAlert to a single JavaScript file using erb templates

### PR DESCRIPTION
**Pull request by svevang**
**REBASED** Tue Dec 15 17:27

This PR removes duplication in the various UIA scripts in run_loop. First, it converts the top level scripts like run_loop_fast_uia.js into erb templates. Then, duplicated code is broken out into sub-templates and included with a erb helper method.

### CODE REVIEW

**Comment by jmoody** [comment]
@krukow @sapieneptus 

I reviewed this @svevang this afternoon.

We ran this version of run-loop on the XTC against the CalSmoke app and locally against the Permissions app (Calabash 2.0).

Before we merge, I need to talk to someone about the XTC internals.

- [ ] Discuss consequences for the XTC
- [ ] Review for JavaScript method renaming
- [ ] Review for JavaScript file renaming
- [ ] Extract template class to file
- [ ] Run the Permissions app on the XTC

**Comment by jmoody** [comment]
Replaces **Feature/refactor onalert javascript** #106

**Comment by jmoody** [comment]
@svevang I merged with the latest develop and fixed the gemspec glob to catch the new lib/*.js files.

**Comment by jmoody** [comment]
@svevang I rebased to resolve conflicts and to add a change to the alert regexes.

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
@svevang Rebased again to stabilize Jenkins builds.

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by jmoody** [comment]
@svevang I am gonna merge!

**Comment by svevang** [comment]
:smiley_cat: :tada:

**Pull request merged**
