### PR TITLE
Fix check for available simulators

### PR DESCRIPTION
**Pull request by akoslowski**
The output format of `xcrun simctl list devices --json` seems to have changed the type of  `isAvailable`. It a boolean value now instead of "YES" or "NO".

```bash
09:56 $ xcrun simctl list devices --json
{
  "devices" : {
    "com.apple.CoreSimulator.SimRuntime.watchOS-5-1" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-12-1" : [

    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-1" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "0C944D5C-DCF5-4FD5-9AD6-34091735FDF0"
      },
      {
        "state" : "Booted",
        "isAvailable" : true,
        "name" : "iPhone 7",
        "udid" : "6D73A12B-F34E-4132-BE05-97355B98506B"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone X",
        "udid" : "5E963272-CE3B-4161-A6EE-EC4F44AF53F5"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xs",
        "udid" : "F7E53429-2B83-4213-9C15-6EC4E3FB7DC7"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air 2",
        "udid" : "5976B5A7-A943-4609-B6E2-C9BFE2243759"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by JoeSSS** [comment]
@jmoody It seems like this was the reason of inability of finding simulator while having 10.1 and 10.2 Xcode installed.

**Comment by JoeSSS** [comment]
@jmoody btw is the CLA still needed? as for OSS project? :)

**Comment by jmoody** [comment]
I think the CLA is still required.

**Pull request merged**
