### PR TITLE
xcode13 fix

### PR DESCRIPTION
**Pull request by AlexeyBudynkov**
In Xcode 13 previous device list acquiring procedure was removed

### CODE REVIEW

**Comment by JoeSSS** [comment]
@AlexeyBudynkov thanks a lot for the contribution! The only difference between the two commands is square vs round brackets around device UDID. Will this create problems? Or we don't use UDID anywhere?

**Review by JoeSSS — APPROVED** [review]

**Comment by AlexeyBudynkov** [comment]
> @AlexeyBudynkov thanks a lot for the contribution! The only difference between the two commands is square vs round brackets around device UDID. Will this create problems? Or we don't use UDID anywhere?

A device UDID is used in iOSDeviceManager integration tests on a physical device. I don't know about a problem with brackets, but with this fix iOSDeviceManager integration tests pass well for solutions built with Xcode 13. Without it no device could be found

**Comment by JoeSSS** [comment]
I see, do you have access to Azure? I don't see why the tests are failing

**Comment by AlexeyBudynkov** [comment]
> I see, do you have access to Azure? I don't see why the tests are failing

I've found one failing place:

Failures:

  1) RunLoop::Instruments#templates Xcode >= 6.0
     Failure/Error: hash = xcrun.run_command_in_context(args, log_cmd: true)

       #<RunLoop::Xcrun:0x00007fc1da0276c0> received :run_command_in_context with unexpected arguments
         expected: (["instruments", "-s", "templates"], {:log_cmd=>true})
              got: (["xctrace", "list", "devices"], {:log_cmd=>true})
       Diff:
       @@ -1 +1 @@
       -[["instruments", "-s", "templates"], {:log_cmd=>true}]
       +[["xctrace", "list", "devices"], {:log_cmd=>true}]
     # ./lib/run_loop/instruments.rb:200:in `block in templates'
     # ./lib/run_loop/instruments.rb:209:in `templates'
     # ./spec/lib/instruments_spec.rb:270:in `block (3 levels) in <top (required)>'

Seems like I changed an extra command in lib/run_loop/instruments.rb

**Comment by AlexeyBudynkov** [comment]
> I see, do you have access to Azure? I don't see why the tests are failing

Tests passed well
https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=1143971&view=results

**Pull request merged**
